### ISSUE TITLE
can-stream proposal

### ISSUE THREAD

**Issue by obaidott** [canjs/can-stream-kefir#24]
# Proposal:

## Goals:
- To create a unified streams API that can be used by DefineMaps
- To make it easy to integrate other stream libraries such as RxJS and Kefir

## Stream API:

**can-stream:**

- __exports__ `function(canStreamInterface)` Exports a function that takes a `canStreamInterface` and returns a `canStreaming` object with the following methods:

 - `.toStream(observable, propAndOrEvent[,event])`
  - `.toStreamFromProperty(property)` ?
  - `.toStreamFromEvent(property)` ?
 - `.toCompute(makeStream(setStream), context):compute`

**canStreamInterface:**

Any `can-stream-X` library should implement the following methods:

- toStream(compute):stream
- toCompute(makeStream(setStream), context):compute

**can-define-stream:**

- __exports__ `function(canStreamInterface)` Exports a function that takes a `canStreamInterface` and returns a function that takes a Type and uses the supplied canStreamInterface to create streamed property definitions and a `.toStream` method.

  __returns__ `function(Type)` That adds the following methods:

  - `DefineMap.prototype.toStream(propAndOrEvent)`
  - `DefineMap.prototype.toCompute(stream)`
  - `DefineMap.prototype.toStreamFromProperty(property)` ?
  - `DefineMap.prototype.toStreamFromEvent(property)` ?

  Finds any `propertyDefinition` with a `stream` behaviour and makes the property take on the value of the stream.

**Usage:**
```js
var canDefineStreamKefir = require("can-define-stream-kefir");
var DefineMap = require("can-define/map/map");
var Person = DefineMap({name: "string"});
canDefineStreamKefir(Person);
```

**Comment by frank-dspeed** [comment]
@phillipskevin can't this be closed as now can-stream and can-stream-kefir exist?

**Comment by frank-dspeed** [comment]
@chasenlehara maybe you can look into this i think can-stream got created already or this is the wrong repo anyway for that proposal
